### PR TITLE
Cache test fix

### LINKED ISSUE #23: Add the imagemagick 6 workaround to the README
As per internal doco

```
$ brew rm imagemagick
$ brew install imagemagick@6 --with-little-cms --with-little-cms2
$ brew link imagemagick@6 --force
$ export PATH=$PATH:$(brew --prefix imagemagick@6)/bin
bundle install
```

### PR DESCRIPTION
**Pull request by bermannoah**
Should alleviate some of the test order issues surrounding the reset_cache_lifetime_seconds! method.

Will also close #23.

### CODE REVIEW

File: spec/image_vise/render_engine_spec.rb [hunk 1]
```diff
@@ -5,6 +5,13 @@
   include Rack::Test::Methods
 
   let(:app) { ImageVise::RenderEngine.new }
+  before :each do
+    ImageVise.reset_cache_lifetime_seconds!
+  end
+
+  after :each do
+    ImageVise.reset_cache_lifetime_seconds!
+  end
```
Comment (julik) [inline spec/image_vise/render_engine_spec.rb]: Is it necesssary to reset after each example, if you are already resetting it before each example?

Comment (bermannoah) [reply spec/image_vise/render_engine_spec.rb]: @julik Fair point! Removed it. Also added the version workaround to the readme.
